## Analisis exploratorio del dataset Iris de Scikit-learn 

- Primer projecto de mi roadmap como AI engineer.
- Objetivo: Analizar el dataset Iris, explorando técnicas varias de manejo y visualización de datos
- Sacar posibles conclusiones de cara al futuro modelado
- Creación en paralelo y uso del repositorio de github


In [58]:
#Importar librerias necesarias

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris

#Configuración estética
sns.set_theme('paper','darkgrid')
plt.rcParams["figure.figsize"]=(10,6)

In [59]:
# Carga del dataset Iris
# como es un dataset local no hay que hacer fetch

iris = load_iris()
print(type(iris))
print("Bunch es como in diccionario Python pero permite acceder a los datos como atributos no solo con []")

<class 'sklearn.utils._bunch.Bunch'>
Bunch es como in diccionario Python pero permite acceder a los datos como atributos no solo con []


## Dataset Iris
Contiene:
- 150 instancias (50 de cada clase)
- Atributos:
    1. Sepal length (cm)
    2. Sepal width (cm)
    3. Petal length (cm)
    4. Petal width (cm)
    5. Clases:
        - Iris-Setosa
        - Iris-Versicolour
        - Iris-Virginica

In [60]:
#Exploración profunda del dataset

#print(iris.keys())
for key in iris.keys():
    print(f"{key}")
    print(getattr(iris, key))
    print("-" * 50)


data
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3

In [61]:
# generar y visualizar el dataframe

df= pd.DataFrame(iris.data,columns= iris.feature_names)

In [62]:
#añadir la colcumna target y target_name(nos permite saber valores asociados al target)
df["target"]= iris.target
df["target_name"]=df['target'].map(lambda i: iris.target_names[i])
df.head


<bound method NDFrame.head of      sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8  

## Exploración general del Dataframe (EDA basico)

- Objetivo conocer la estructura y distribucion general de los datos de cara al modelado


In [71]:
#Información general del dataframe

print("dimensiones del dataset:",df.shape)
print("data types:", df.dtypes)

#Conteo de cada clase
print(df['target'].value_counts())
print(df.describe())

dimensiones del dataset: (150, 6)
data types: sepal length (cm)    float64
sepal width (cm)     float64
petal length (cm)    float64
petal width (cm)     float64
target                 int64
target_name           object
dtype: object
target
0    50
1    50
2    50
Name: count, dtype: int64
       sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)      target  
count        150.000000  150.000000  
mean           1.199333    1.000000  
std      